// Mocks generated by Mockito 5.4.6 from annotations
// in thingviewer/test/screens/pinned_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:thingviewer/api/thingspeak_api.dart' as _i3;
import 'package:thingviewer/models/channel.dart' as _i2;
import 'package:thingviewer/models/field.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeChannel_0 extends _i1.SmartFake implements _i2.Channel {
  _FakeChannel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFeedData_1 extends _i1.SmartFake implements _i3.FeedData {
  _FakeFeedData_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeField_2 extends _i1.SmartFake implements _i4.Field {
  _FakeField_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFieldRange_3 extends _i1.SmartFake implements _i3.FieldRange {
  _FakeFieldRange_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ThingSpeakApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockThingSpeakApi extends _i1.Mock implements _i3.ThingSpeakApi {
  MockThingSpeakApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Channel> readChannel(_i2.Channel? channel) =>
      (super.noSuchMethod(
            Invocation.method(#readChannel, [channel]),
            returnValue: _i5.Future<_i2.Channel>.value(
              _FakeChannel_0(this, Invocation.method(#readChannel, [channel])),
            ),
          )
          as _i5.Future<_i2.Channel>);

  @override
  _i5.Future<_i3.FeedData> readFeed(
    _i2.Channel? channel,
    _i3.ApiParameters? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#readFeed, [channel, params]),
            returnValue: _i5.Future<_i3.FeedData>.value(
              _FakeFeedData_1(
                this,
                Invocation.method(#readFeed, [channel, params]),
              ),
            ),
          )
          as _i5.Future<_i3.FeedData>);

  @override
  _i5.Future<_i4.Field> readField(
    _i2.Channel? channel,
    int? fieldId,
    _i3.ApiParameters? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#readField, [channel, fieldId, params]),
            returnValue: _i5.Future<_i4.Field>.value(
              _FakeField_2(
                this,
                Invocation.method(#readField, [channel, fieldId, params]),
              ),
            ),
          )
          as _i5.Future<_i4.Field>);

  @override
  _i5.Future<_i4.FieldValue?> readLastFieldEntry(
    _i2.Channel? channel,
    int? fieldId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#readLastFieldEntry, [channel, fieldId]),
            returnValue: _i5.Future<_i4.FieldValue?>.value(),
          )
          as _i5.Future<_i4.FieldValue?>);

  @override
  _i5.Future<_i3.FieldRange> readFieldRange(
    _i2.Channel? channel,
    int? fieldId, {
    String? apiKey,
    required DateTime? start,
    required DateTime? end,
    void Function(int)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #readFieldRange,
              [channel, fieldId],
              {
                #apiKey: apiKey,
                #start: start,
                #end: end,
                #onProgress: onProgress,
              },
            ),
            returnValue: _i5.Future<_i3.FieldRange>.value(
              _FakeFieldRange_3(
                this,
                Invocation.method(
                  #readFieldRange,
                  [channel, fieldId],
                  {
                    #apiKey: apiKey,
                    #start: start,
                    #end: end,
                    #onProgress: onProgress,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i3.FieldRange>);
}
